### ISSUE TITLE
Offchain workers - bug

### ISSUE THREAD

**Issue by korzewski** [atomiklabs/jackblock-node#23]
Currently after each session finalisation, there is an extra pending extrinsic. This number grows over the time to infinite number.

Similar thing with NFT offchain worker, even when condition is not fired - there is a call for unsigned_transaction every block...

### Requirements
- Check if there is no logic error when sending signed payload
- Maybe implementing a lock at the beginning of offchain worker would solve the problem?

**Comment by tk-o** [comment]
This issue is quite important to fix ASAP, as our servers get literally stuck with ever-growing OCW calls backlog.

I did some reading, and here's an example of how potentially we could throttle the OCW invocations: https://github.com/paritytech/substrate/blob/67adfea6f6cf0a7cb1b4a955c17c2280c097a445/frame/election-provider-multi-phase/src/unsigned.rs#L351-L381
